local curstatestr=`"`1'"'

* Generate a variable for statefip code
gen statefip = .

* Map state names to statefip codes using replace
replace statefip = 1 if `"`curstatestr'"'== "Alabama"
replace statefip = 2 if `"`curstatestr'"'== "Alaska"
replace statefip = 4 if `"`curstatestr'"'== "Arizona"
replace statefip = 5 if `"`curstatestr'"'== "Arkansas"
replace statefip = 6 if `"`curstatestr'"'== "California"
replace statefip = 8 if `"`curstatestr'"'== "Colorado"
replace statefip = 9 if `"`curstatestr'"'== "Connecticut"
replace statefip = 10 if `"`curstatestr'"'== "Delaware"
replace statefip = 12 if `"`curstatestr'"'== "Florida"
replace statefip = 13 if `"`curstatestr'"'== "Georgia"
replace statefip = 15 if `"`curstatestr'"'== "Hawaii"
replace statefip = 16 if `"`curstatestr'"'== "Idaho"
replace statefip = 17 if `"`curstatestr'"'== "Illinois"
replace statefip = 18 if `"`curstatestr'"'== "Indiana"
replace statefip = 19 if `"`curstatestr'"'== "Iowa"
replace statefip = 20 if `"`curstatestr'"'== "Kansas"
replace statefip = 21 if `"`curstatestr'"'== "Kentucky"
replace statefip = 22 if `"`curstatestr'"'== "Louisiana"
replace statefip = 23 if `"`curstatestr'"'== "Maine"
replace statefip = 24 if `"`curstatestr'"'== "Maryland"
replace statefip = 25 if `"`curstatestr'"'== "Massachusetts"
replace statefip = 26 if `"`curstatestr'"'== "Michigan"
replace statefip = 27 if `"`curstatestr'"'== "Minnesota"
replace statefip = 28 if `"`curstatestr'"'== "Mississippi"
replace statefip = 29 if `"`curstatestr'"'== "Missouri"
replace statefip = 30 if `"`curstatestr'"'== "Montana"
replace statefip = 31 if `"`curstatestr'"'== "Nebraska"
replace statefip = 32 if `"`curstatestr'"'== "Nevada"
replace statefip = 33 if `"`curstatestr'"'== "New Hampshire"
replace statefip = 34 if `"`curstatestr'"'== "New Jersey"
replace statefip = 35 if `"`curstatestr'"'== "New Mexico"
replace statefip = 36 if `"`curstatestr'"'== "New York"
replace statefip = 37 if `"`curstatestr'"'== "North Carolina"
replace statefip = 38 if `"`curstatestr'"'== "North Dakota"
replace statefip = 39 if `"`curstatestr'"'== "Ohio"
replace statefip = 40 if `"`curstatestr'"'== "Oklahoma"
replace statefip = 41 if `"`curstatestr'"'== "Oregon"
replace statefip = 42 if `"`curstatestr'"'== "Pennsylvania"
replace statefip = 44 if `"`curstatestr'"'== "Rhode Island"
replace statefip = 45 if `"`curstatestr'"'== "South Carolina"
replace statefip = 46 if `"`curstatestr'"'== "South Dakota"
replace statefip = 47 if `"`curstatestr'"'== "Tennessee"
replace statefip = 48 if `"`curstatestr'"'== "Texas"
replace statefip = 49 if `"`curstatestr'"'== "Utah"
replace statefip = 50 if `"`curstatestr'"'== "Vermont"
replace statefip = 51 if `"`curstatestr'"'== "Virginia"
replace statefip = 53 if `"`curstatestr'"'== "Washington"
replace statefip = 54 if `"`curstatestr'"'== "West Virginia"
replace statefip = 55 if `"`curstatestr'"'== "Wisconsin"
replace statefip = 56 if `"`curstatestr'"'== "Wyoming"
